name: Failing Workflow
on:   # yamllint disable-line rule:truthy
  push: {}
  workflow_dispatch: {}
jobs:
  test:
    name: Checkout and Setup
    timeout-minutes: 2
    runs-on: windows-latest
    steps:
    - run: where.exe yarn
    - run: type C:\npm\prefix\yarn.cmd
    - uses: actions/checkout@v3
    - run: C:\npm\prefix\yarn.cmd --version --verbose
      env:
        DEBUG: '*'
        NODE_DEBUG: '*'
